// This file is auto-generated by the Tapowan Public School Server (.exe)
// It tells the mobile app and GitHub Pages website where to connect.
window.API_BASE_URL = "https://tapowan-school.loca.lt";
